blog/urls.py
from django.urls import path
from django.views.generic.base import View
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'  # Define the application name space. This allows to organize URLS by application and use the name when referring to them

urlpatterns = [
    # Post view
    path(route='', view=views.post_list, name='post_list'),
    # path(route='', view=views.PostListView.as_view(), name='post_list'),
    path(route='<int:year>/<int:month>/<int:day>/<slug:post>',
         view=views.post_detail, name='post_detail'),
    path(route='<int:post_id>/share/', view=views.post_share, name='post_share'),
    path(route='tag/<slug:tag_slug>/',
         view=views.post_list, name='post_list_by_tag'),
    path(route='feed/', view=LatestPostsFeed(), name='post_feed')
]

config/urls.py
from django.contrib import admin, sitemaps
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap

sitemaps = {
    'posts': PostSiteMap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path(
        route='sitemap.xml',
        view=sitemap,
        kwargs={
            'sitemaps': sitemaps
        },
        name='django.contrib.sitemaps.view.sitemap'
    )
]

blog/models.py
from django.db import models
from django.urls.base import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import activate

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)  # post title

    slug = models.SlugField(
        max_length=250, unique_for_date='publish')  # for URL

    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )

    body = models.TextField()  # body of the post
    publish = models.DateTimeField(default=timezone.now)  # time of publishing
    created = models.DateTimeField(auto_now_add=True)  # time of creation
    updated = models.DateTimeField(auto_now=True)  # time of update

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft'
    )

    class Meta:
        # sort results by publish field in descending order (-) when query database
        ordering = ('-publish',)

    def __str__(self):
        return self.title  # for better representation in adminitration site

    def get_absolute_url(self):
        return reverse(
            viewname='blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Custom manager
    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    # is rendered as an <input type="text">
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')  # Only include these fields in form

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    # Get all posts with the published status using published manager is created.
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        # get Tag object with the given slug
        tag = get_object_or_404(Tag, slug=tag_slug)
        # filter list of posts with this given tag
        object_list = object_list.filter(tags__in=[tag])

    # Instantiate with the number of objects to display
    paginator = Paginator(object_list, 3)  # posts in each page

    # Get the current page
    page = request.GET.get('page')
    try:
        # obtain the object for desired page
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request=request,
        template_name='blog/post/list.html',
        context={
            'page': page,
            'posts': posts,
            'tag': tag
        }
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,  # There is only one slug for a given day, because of unique_for_date
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Get all active comments of this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Retrieve a python list of IDs for tags of the current post.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)  # exclude the current post

    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    return render(
        request=request,
        template_name='blog/post/detail.html',
        context={
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts': similar_posts,
        }
    )


def post_share(request, post_id):
    # Retrieve post by id, make sure it is published
    post = get_object_or_404(
        Post,
        id=post_id,
        status='published'
    )

    sent = False

    # Use same view for both displaying the initial form and processing the submitted data

    if request.method == 'POST':
        # Form was submitted, create a from with data is contained in request.POST
        form = EmailPostForm(request.POST)
        # Validate the submitted data, True if all fields contain valid data
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(
                subject=subject,
                message=message,
                from_email='admin&email.com',
                recipient_list=[cd['to']]
            )
            sent = True
    else:
        # Empty form is requested
        form = EmailPostForm()
    return render(
        request=request,
        template_name='blog/post/share.html',
        context={
            'post': post,
            'form': form,
            'sent': sent
        })

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
</head>

<body>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>

        <p>
            <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>
        </p>

        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title}} </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h1>
    {{ post.title}}
</h1>
<p class="date">
    Published {{ post.publish }} by {{post.author}}
</p>
{{post.body|linebreaks}}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
</p>

<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href=" {{ post.get_absolute_url }} ">
        {{ post.title}}
    </a>
</p>

{% empty %}
There are no similar posts yet.
{% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{comment.name}}
        {{ comment.created}}
    </p>
    {{ comment.body|markdown }}
</div>

{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="" method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p>
        <input type="submit" value="Add comment">
    </p>
</form>
{% endif %}

{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
My Blog
{% endblock title %}

{% block content %}
<h1>My Blog</h1>
{% if tag %}
<h2>Posts tagged with "{{tag.name}}" </h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30}}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% comment %} {% include "pagination.html" with page=page_obj %} {% endcomment %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock title %}

{% block content %}
{% if sent %}
<h1>E-mail successfully sent.</h1>
<p>
    "{{ post.title}}" was successfully sent to {{ form.cleaned_data.to}}.
</p>
{% else %}
<h1>Share "{{ post.title}}" by e-mail.</h1>
<form action="" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">

        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number}}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}

    </span>
</div>